FROM openjdk:17
ADD target/SpringBootProjectWithGson-0.0.1-SNAPSHOT.jar SpringBootProjectWithGson-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","SpringBootProjectWithGson-0.0.1-SNAPSHOT.jar"]