apiVersion: v1
kind: Service
metadata:
  name: springbootwithgson-service-name
spec:
  selector:
    app: springbootwithgson-pod-label
  ports:
    - protocol: TCP
      port: 80  # Expose on port 80 (externally)
      targetPort: 8080  # Forward to port 8080 (container)
  type: NodePort  # This exposes it externally
